### ISSUE TITLE
Creating tables

### ISSUE THREAD

**Issue by glenfordwilliams** [christopher-ramirez/secretary#13]
Do you have an example of using a table with secretary? all the methods i tried seemed to create errors or extra rows in between

**Comment by christopher-ramirez** [comment]
Hello @glenfordwilliams!

`simple_template.odt` contains simple and semi-complex tables. What methods are you trying?

**Comment by glenfordwilliams** [comment]
my bad i thought i could just jump in using jinja but didnt realize that all the jinja markings were used as fields

**Comment by christopher-ramirez** [comment]
Glad to hear you could resolve the issue.
