### ISSUE TITLE
Text style tags not always properly stripped from template elements

### ISSUE THREAD

**Issue by DieterBuysAI** [christopher-ramirez/secretary#16]
In particular, secretary has difficulty parsing statements such as ```{% if [1, 2, 3]|length > 0 %}Foo Bar{% endif %}``` because OpenOffice likes to insert text styling tags around the square brackets. Small tweak to the `_unescape_entities` method can fix this.

**Comment by christopher-ramirez** [comment]
What specifically styling tags is OpenOffice inserting around square brackets? I could not reproduce this issue on Libreoffice. The sample statement is stored as **`{% if [1, 2, 3]|length &gt; 0 %}Foo Bar{% endif %}`**  (just replacing greater-than symbol with `&gt;` as expected.

**Comment by DieterBuysAI** [comment]
Actually I was using LibreOffice too. I don't have the template data handy now but whenever I wrote `[` or `]` then LibreOffice Writer would insert `<text:span>` tags around it. In general any styling tags inside the `{% ... %}` or `{{ ... }}` should be ignored, no?

**Comment by christopher-ramirez** [comment]
Thank for your contribution and help. I've uploaded a new version fixing issues #14 and #16.

**Comment by DieterBuysAI** [comment]
Pleased to be of service @christopher-ramirez
