### ISSUE TITLE
Error in secretary.py

### ISSUE THREAD

**Issue by nothingalike** [christopher-ramirez/secretary#25]
```Line 466: self.log.error('Unescaped template was:\n{}'.format(template_string))```
you are missing your parameter, needs to be
```Line 466: self.log.error('Unescaped template was:\n{0}'.format(template_string))```

**Comment by christopher-ramirez** [comment]
Thank @nothingalike. I will give it a look.

**Comment by nothingalike** [comment]
One thing after talking to some colleagues, we are using python 2.6.

**Comment by nothingalike** [comment]
Awesome. When do you think this will be ready?

**Comment by christopher-ramirez** [comment]
I don't want to create a new version just including this fix. I've been thinking in refactoring some stuff for a new build but I haven't much time lately. Also, I need to review PR #22 and #24.
