### ISSUE TITLE
Markdown and line breaks

### ISSUE THREAD

**Issue by ak04nv** [christopher-ramirez/secretary#47]
After this [manipulation](https://github.com/christopher-ramirez/secretary/blob/master/secretary.py#L755) I get an escaped line breaks (`\n` converts to `\\n`) and then I see `\n` as text in my odt file instead of new line. Also `\n\n` converts to `\\n\\n`.
I'm not sure about `\t` but I think it has the same issue.

**Comment by christopher-ramirez** [comment]
Hello! Thank you for reporting this. I will be checking it today and hope to have a fix asap.

**Comment by christopher-ramirez** [comment]
Hello! May you please provide a more in depth explanation of the issue at hand. I quite don't understand what you are reporting.

**Comment by ak04nv** [comment]
@christopher-ramirez Try this text:
```
ОАК от 08.09.2017: Лейк 7.9х10^9/л; Hb х 136г/л; Эр 3,96 х 10^12/л; Тром 174 х 10^9/л
ОАМ от 08.09.2017: Цвет- сол.жел. Уд.вес 1015 Белок- отриц Рh 6.0
Группа крови: 0 (1) СсДЕе
Б\Х от 08.09.2017 Сах.крови 4.9; Мочевина 3.5; Билирубин 10.3

Заведующий отделением: Медведников А.А.
_врач Захаров Антон Геннадьевич_
```

**Comment by christopher-ramirez** [comment]
I can see the output is as spectated with the provided sample. Can you please clarify the issue?

See [this markdown output](https://jbt.github.io/markdown-editor/#bY9dSsNAFIXfs4r7qGDHSdMf027ARUgLPrmMtCUWQaSliqBF/EHfhFgbSdMft3DujjwzLQgimQRyz7nnO4MHjHAn2Ghf7JGxsanasNkS3CPHAqU0TaxpaDvxIZZtOT4VTSWMGvj0/3jXRKKDuOHHthNWt+NnTbDBSsJmbae4/QCONv2H9oYZcu1XRHvcWxp8Eb80ghfMjdd6DAnrgrET6CkrPoacQs8Fj2fSMDbARBMd4JtPJih9ixmKlljZC/cFT8y/xg3yAOMTvP5tQgMyTc3vptRMzPtMaRySzAnWjI5Mve26FOxSeOSHU9jRREGAW2SuNOY60Cu9oLTwKMx9+5wZBb+rlkumbWv209JxBSPDE3QxY5FMh+IiNeWb7HSsGbchEhOfx1bEXW476rD7Aw==).

**Comment by ak04nv** [comment]
@christopher-ramirez I'm sorry, I mean try to pass through the markdown filter in odt template. I've made a [repo on github](https://github.com/ak04nv/secretary-47-issue) for explain this issue.
The result you can see on this [screenshot](https://ibb.co/gtg015).

**Comment by ak04nv** [comment]
@christopher-ramirez Thanks for quick answer!
I guess I've catched the bug. Try to clone this repo again and run test.py
The difference between python versions. You use python2 (I think), but I use python3.5
I've run this code in python2 and it works fine! But in python3 I've gotten the result as on the screenshot above.

**Comment by christopher-ramirez** [comment]
Hello I could reproduce the issue on Py3. I will check your fix and merge it.

Thanks for your help.
