### ISSUE TITLE
Explain how add page

### ISSUE THREAD

**Issue by fturiot** [christopher-ramirez/secretary#58]
Hello,
Is it possible to add page (with one page template ) 
example 
Page one cover 
page two general information

page 3 to n  detail information 
page n+1 end page
thanks for all

**Comment by christopher-ramirez** [comment]
Hello! N pages can be added immediately after a loop tag. eg:

`{% for profile in profiles %}`*[insert a page break here with CTRL+Enter]*

**[ detail page ]**

`{% endfor %}`*[insert a page break here]*

**[ end page ]**

Hope this helps

**Comment by fturiot** [comment]
thanks for all
