### ISSUE TITLE
page break

### ISSUE THREAD

**Issue by massimiliano-dalcero** [christopher-ramirez/secretary#60]
is possible add a "page break" like:

{{page_break}}?

I have put the end of the "for" in new page, but for work is need to add a "blank line" up to first line and this make a page with the first line as blank.

I need ti create new page without white line :)

this don't create new page

> {% for iten in datas.item %}
> write some things... 
> --- page_break via LibreOffice ---
> {% endfor %}

this work,  but create a ne blank line inside new page :(

> {% for iten in datas.item %}
> write some things... 
> --- page_break via LibreOffice ---
> 
> {% endfor %}

**Comment by christopher-ramirez** [comment]
Please see #58 for instructions of how to properly add a page break. It may help you.

Regards,
