### ISSUE TITLE
TemplateSyntaxError at /generate/document/  unexpected '<'

### ISSUE THREAD

**Issue by CGurity** [christopher-ramirez/secretary#62]
Hello!
I'm trying to replicate your example in an existing app and I'm having this error, I tried many things but nothing is working, even replacing the query for a list the complete error below:

Request Method: | GET
--|--
Request URL: | https://xxxxxxxxxx.com/generate/document/
Django Version: | 1.8.18
Exception Type: |  TemplateSyntaxError
Exception Value: | unexpected '<'
Exception Location: | /home/.../lib/python3.5/jinja2/parser.py in fail, line 59
Python Executable: | /usr/local/bin/python3
Python Version: | 3.5.5
Python Path: | ['...']
Server time: | Sat, 24 Feb 2018 00:25:59 +0000

There is something I could be missing?
Thank you in advance!

**Comment by christopher-ramirez** [comment]
Hello

This exception is raised because in your template you have a problem is your syntax.

**Comment by enricofer** [comment]
Now I see what you mean when you say "Secretary recommends using an alternative way of inserting fields." in https://github.com/christopher-ramirez/secretary/blob/master/README.md#composing-templates
