### ISSUE TITLE
more cells in the final render of table

### ISSUE THREAD

**Issue by med1143** [christopher-ramirez/secretary#64]
Hi,

I do not understand how I have more cells in the construction of my table ?
![capture d ecran_2018-03-15_00-26-45](https://user-images.githubusercontent.com/4864210/37436411-1bd7f716-27e8-11e8-9078-fc9d852a70d6.png)

result:
![capture d ecran_2018-03-15_00-27-18](https://user-images.githubusercontent.com/4864210/37436433-3e18a168-27e8-11e8-860e-ddb98a8fa46d.png)

Can you help me ?

Thank you for your efforts, secretary is so cool !

**Comment by christopher-ramirez** [comment]
Hello!

Thank you! What I can see from the screenshots is that your are not using an input field for the `for` loop tag.

Hope this helps

**Comment by med1143** [comment]
Thank you for your response.

I modified with input field the for loop but it is the same result  !

When i use your example inside my doc, it works. I think that i forget a detail when i contruct my table.

An other idea ?

**Comment by christopher-ramirez** [comment]
Does the screenshot displays the whole table, or just a part of it?

**Comment by med1143** [comment]
It's just part.

I join a odt file in a doc.zip
[doc.zip](https://github.com/christopher-ramirez/secretary/files/1815984/doc.zip)


Thank you

**Comment by christopher-ramirez** [comment]
I took a check on the template. I saw that you repeat the loop logic on the *Reference* property of the fields. Please clear the reference property since they are not required.

Thank may solve your problem.

**Comment by med1143** [comment]
It works, thank you very much and good luck !
