### ISSUE TITLE
Web server need to install libreoffice or openoffice?

### ISSUE THREAD

**Issue by GaryChiang** [christopher-ramirez/secretary#65]
Hi ,

I am using secretary right now. But I still have one question.

I have already installed libreoffice in my computer to develop report.

Do I need to installed libreoffice in the web server?

**Comment by christopher-ramirez** [comment]
Hello,

No. You do not need LibreOffice installed on the server for rendering documents. But if you want to convert those documents to other formats (DOC, PDF, etc) you will need at least a headless install of [Libre/Open]Office.

**Comment by GaryChiang** [comment]
thanks it's helpful.
