### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mareb** [christopher-ramirez/secretary#70]
Hello,
I try to install:

$ pip install secretrary
Collecting secretrary
  Could not find a version that satisfies the requirement secretrary (from versions: )
No matching distribution found for secretrary

What is needed before that command?

Thank you

**Comment by christopher-ramirez** [comment]
Hello, hard to tell with the little information you are providing. Could please share a complete log output?

**Comment by mareb** [comment]
Sorry, but this IS the full output!

I done a git clone. Then I call that from secretary directory.
Using XUbuntu 18.04

Thank you for looking at that problem!

Manfred

**Comment by christopher-ramirez** [comment]
Then I think that the issue may arrive for running the `pip install` inside the repo directory. Try to run the command inside of the directory of the project where you intend to use Secretary.
